import { describe, expect, it } from 'vitest';
import { isAllowed, parseRobots } from './robots';

// Trimmed copy of https://hololive.wiki/robots.txt as served in October 2026.
const HOLOLIVE_WIKI = `
# robots.txt for Miraheze, autogenerated by robots.php
User-agent: *
Allow: /w/api.php?action=mobileview&
Allow: /w/load.php?
Disallow: /w/
Disallow: /geoip
Disallow: /rest_v1/
Disallow: /*?action=
Disallow: /*?*&action=
Disallow: /wiki/Special:
Disallow: /Special:

User-agent: SemrushBot
Disallow: /
`;

describe('parseRobots', () => {
  it('reads only the wildcard group', () => {
    const rules = parseRobots(HOLOLIVE_WIKI);
    expect(rules.allow).toEqual(['/w/api.php?action=mobileview&', '/w/load.php?']);
    expect(rules.disallow).toContain('/w/');
    expect(rules.disallow).not.toContain('/');
  });

  it('treats a missing or empty file as allow-all', () => {
    expect(isAllowed(parseRobots(''), '/anything')).toBe(true);
  });
});

describe('isAllowed against the real hololive.wiki rules', () => {
  const rules = parseRobots(HOLOLIVE_WIKI);

  it('allows the article pages the scraper reads', () => {
    expect(isAllowed(rules, '/wiki/Membership_Emotes')).toBe(true);
    expect(isAllowed(rules, '/wiki/Membership_Emotes/Hololive_English')).toBe(true);
    expect(isAllowed(rules, '/wiki/Membership_Emotes/Hololive_(Japan)')).toBe(true);
  });

  it('rejects the API calls the old scraper made', () => {
    expect(isAllowed(rules, '/w/api.php?action=parse&page=Membership_Emotes&prop=sections&format=json')).toBe(false);
    expect(isAllowed(rules, '/w/api.php')).toBe(false);
  });

  it('rejects action URLs and special pages anywhere', () => {
    expect(isAllowed(rules, '/wiki/Membership_Emotes?action=raw')).toBe(false);
    expect(isAllowed(rules, '/wiki/Foo?x=1&action=edit')).toBe(false);
    expect(isAllowed(rules, '/wiki/Special:Export/Membership_Emotes')).toBe(false);
  });

  it('lets a longer Allow override a shorter Disallow', () => {
    expect(isAllowed(rules, '/w/api.php?action=mobileview&page=Membership_Emotes')).toBe(true);
    expect(isAllowed(rules, '/w/load.php?modules=startup')).toBe(true);
  });
});

describe('isAllowed pattern syntax', () => {
  it('supports $ anchors and mid-pattern wildcards', () => {
    const rules = parseRobots('User-agent: *\nDisallow: /*.json$\nDisallow: /private*/data');
    expect(isAllowed(rules, '/emotes/en.json')).toBe(false);
    expect(isAllowed(rules, '/emotes/en.json?v=2')).toBe(true);
    expect(isAllowed(rules, '/private-stuff/data')).toBe(false);
    expect(isAllowed(rules, '/public/data')).toBe(true);
  });
});
